language: elixir

elixir:
  - 1.8.1

otp_release:
  - 21.1

matrix:
  include:
  - otp_release: 19.3
    elixir: 1.6.1

script:
  - MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json
  - MIX_ENV=test mix do deps.get, compile, coveralls.travis

after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
  - bash <(curl -s https://codecov.io/bash)
