language: elixir

elixir:
  - 1.8.1

otp_release:
  - 21.1

matrix:
  include:
  - otp_release: 19.3
    elixir: 1.7.0

script:
  - MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json

after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
  - bash <(curl -s https://codecov.io/bash)
  - MIX_ENV=test mix coveralls.travis
